application:
  appId: GAZER-123
  assetId: GAZER-123
  sdlcType: EDM
  appType: Webapp
  webservice: false
  restApi: true
  microservice: false
  projectLanguage: Java
  frameworks: 
   - Spring security
   - Hibernate
  platformVersion: Java 8
  buildSystem: Maven
  riskMatrixRevision: Rev1.0
  sourceFilePattern: ".*\\+\\+\\+.*(\\.java|\\.jsp)+.*"
  sensitivePackagePattern: ".*(\\+\\+\\+.*(org\\/hdivsamples\\/security)).*"
  fileChangeThreshold: 20

environment:
  scm: GitLab
  gitlabHostUrl: "https://sig-gitlab.internal.synopsys.com/"
  gitlabToken: "eNFmjaTxT9nsvd3nuvFr"
  scmOwner: "akshayme"
  scmRepositoryName: "Stargazer-IQ"
  scmBranchName: "stargazer-on-stargazer"
  testDeploymentRoot: "Stargazer-IQ"
  imChannelIdentifier: "#stargazer-notifications"
  jiraProjectName: "DEM"
  jiraIssuesQuery: "resolution = \"Unresolved\" AND labels in (Security, Defect)"
